### ISSUE TITLE
get high-quality scans of Lacombe's dictionary

### ISSUE THREAD

**Issue by dwhieb** [UAlbertaALTLab/dictionary-database#13]
Get high-quality scans of Lacombe's dictionary.

[Project Notes (Google Drive)](https://docs.google.com/document/d/1i3xCbYQtJN6ZwJgFm_XXWKhx5DR86P-yKVIQUizp7j8/edit)

Currently-available downloads:

* https://ia902806.us.archive.org/view_archive.php?archive=/3/items/dictionnairedela01laco/dictionnairedela01laco_orig_jp2.tar
* https://numerique.banq.qc.ca/patrimoine/details/52327/3994014
* https://drive.google.com/drive/folders/1AtauHmz8qh_Bfp0YvyZsGhb9IioeiTSl?usp=sharing

**Comment by aarppe** [comment]
I had preliminary discussions about with Sharon Farnel, of the UofA Library, about getting either their existing scans of LDC, or creating new, better-quality scans, but those discussions stalled last spring. I can resurrect that discussion now.

**Comment by dwhieb** [comment]
Closing this issue because we don't want to track progress on this project in GitHub issues unless it actually involves changing the code in this repo. #7 can serve as the general metaissue for this project.
