### ISSUE TITLE
matching MD <ts> cases with CW <c> or <ci> cases

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/dictionary-database#3]
Besides the straight-forward linking of MD and CW content by undoing vowel length for CW dictionary entries and converting `<ch>` to `<c>` and turning prefix-spaces to hyphens for MD entries, there are other orthographical divergences that are not as systematic and thus harder to match. One of the more frequent ones is the MD convention of using `<ts>` for either `<c>` or `<ci>` in CW. So, while this can be automated for a large part, it will need manual final fixing and validation.

An example MD _mitsow_ 'He eats.' which is not matched with CW _mîcisow_.

A similar but less observed variation is MD using a short `<i>` for an unstressed short vowel such as `<a>` in CW, e.g. MD _wapimew_ is not matched with CW _wâpamêw_ - there might be other CW short vowels rendered as `<i>` in MD as well.

**Comment by dwhieb** [comment]
These notes have been incorporated into #5. Closing this issue.
