### ISSUE TITLE
orthographic normalization

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/dictionary-database#4]
The above cases illustrate that in matching MD with CW, there are some minor but still significant orthographical differences, which result in certain matches not being made that should be identified.

E.g. MD _mitsow_ 'He eats.' is not matched with CW _mîcisow_, and likewise MD _wapimew_ is not matched with CW _wâpamêw_.

This probably should be made into its own issue, but under the Dictionary Database project.

_Originally posted by @aarppe in https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/issues/197#issuecomment-598526189_

**Comment by dwhieb** [comment]
Incorporated this into the notes for #5. Closing this issue.
